export const SHOW_PEDIDOS_USER = "SHOW_PEDIDOS_USER";
export const NEW_PEDIDO_USER = "NEW_PEDIDO_USER";
export const FETCH_RENTALS_SUCCESS = "FETCH_RENTALS_SUCCESS";
export const FETCH_RENTALS_FAIL = "FETCH_RENTALS_FAIL";
export const NEW_RENTAL_SUCCESS = "NEW_RENTAL_SUCCESS";
export const NEW_RENTAL_FAIL = "NEW_RENTAL_FAIL";


export const SET_ERROR = "SET_ERROR";
export const HIDE_ERROR = "HIDE_ERROR";